services:
  # Frontend React
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_AUTH_API_URL=http://localhost:5001
      - VITE_PREDICTION_API_URL=http://localhost:5002  
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  # API d'Authentification
  auth-api:
    build: ./auth-api
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./auth-api:/app
      - ./shared/data:/app/shared/data  # Pour la base de données
    restart: unless-stopped

  # API de Prédiction
  prediction-api:
    build: ./prediction-api
    ports:
      - "5002:5002"
    env_file:
      - .env
    volumes:
      - ./prediction-api:/app
      - ./shared/data:/app/data
      - ./shared/models:/app/shared/models 
    restart: unless-stopped

  # Reverse Proxy Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - auth-api
      - prediction-api
    restart: unless-stopped